# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sunil Kumar
email: sunilsrix@gmail.com
description: "A constant quest to learn every day, every hour and everyminute.
Technology is an integral part of my life and it reflects in almostevery facets
of life."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: sunilsrikumar
github_username:  sunilsrikumar

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/


google_analytics: UA-54785341-1
repo: http://github.com/sunilsrikumar/blog
disqus_shortname: "sunilsrikumar"
